
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IFineService", targetNamespace = "http://siv.api.FineService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFineService {


    /**
     * 
     * @param finesData
     * @return
     *     returns hello.FinesResponseData
     */
    @WebMethod(operationName = "GetFines", action = "http://siv.api.FineService/IFineService/GetFines")
    @WebResult(name = "GetFinesResult", targetNamespace = "http://siv.api.FineService")
    @RequestWrapper(localName = "GetFines", targetNamespace = "http://siv.api.FineService", className = "hello.GetFines")
    @ResponseWrapper(localName = "GetFinesResponse", targetNamespace = "http://siv.api.FineService", className = "hello.GetFinesResponse")
    public FinesResponseData getFines(
        @WebParam(name = "finesData", targetNamespace = "http://siv.api.FineService")
        FinesRequestData finesData);

}
