
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IFineService", targetNamespace = "http://siv.api.FineService", wsdlLocation = "file:/home/eliotte/dev/test/src/main/resources/FineServiceClass.wsdl")
public class IFineService_Service
    extends Service
{

    private final static URL IFINESERVICE_WSDL_LOCATION;
    private final static WebServiceException IFINESERVICE_EXCEPTION;
    private final static QName IFINESERVICE_QNAME = new QName("http://siv.api.FineService", "IFineService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/eliotte/dev/test/src/main/resources/FineServiceClass.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IFINESERVICE_WSDL_LOCATION = url;
        IFINESERVICE_EXCEPTION = e;
    }

    public IFineService_Service() {
        super(__getWsdlLocation(), IFINESERVICE_QNAME);
    }

    public IFineService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IFINESERVICE_QNAME, features);
    }

    public IFineService_Service(URL wsdlLocation) {
        super(wsdlLocation, IFINESERVICE_QNAME);
    }

    public IFineService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IFINESERVICE_QNAME, features);
    }

    public IFineService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IFineService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFineService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFineService")
    public IFineService getBasicHttpBindingIFineService() {
        return super.getPort(new QName("http://siv.api.FineService", "BasicHttpBinding_IFineService"), IFineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFineService
     */
    @WebEndpoint(name = "BasicHttpBinding_IFineService")
    public IFineService getBasicHttpBindingIFineService(WebServiceFeature... features) {
        return super.getPort(new QName("http://siv.api.FineService", "BasicHttpBinding_IFineService"), IFineService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IFINESERVICE_EXCEPTION!= null) {
            throw IFINESERVICE_EXCEPTION;
        }
        return IFINESERVICE_WSDL_LOCATION;
    }

}
